# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ear_raport.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from sys import platform
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.outer_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.outer_stackedWidget.setEnabled(True)
        self.outer_stackedWidget.setObjectName("outer_stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.login_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.login_page)
        self.frame.setMaximumSize(QtCore.QSize(400, 200))
        self.frame.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.name_lineEdit.setToolTipDuration(0)
        self.name_lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name_lineEdit.setInputMask("")
        self.name_lineEdit.setText("")
        self.name_lineEdit.setMaxLength(20)
        self.name_lineEdit.setClearButtonEnabled(True)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.gridLayout_2.addWidget(self.name_lineEdit, 0, 0, 1, 1)
        self.surname_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.surname_lineEdit.setClearButtonEnabled(True)
        self.surname_lineEdit.setObjectName("surname_lineEdit")
        self.gridLayout_2.addWidget(self.surname_lineEdit, 1, 0, 1, 1)
        self.enter_button = QtWidgets.QPushButton(self.frame)
        self.enter_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.enter_button.setAutoFillBackground(False)
        self.enter_button.setObjectName("enter_button")
        self.gridLayout_2.addWidget(self.enter_button, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.outer_stackedWidget.addWidget(self.login_page)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.main_page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.raport_button = QtWidgets.QPushButton(self.frame_2)
        self.raport_button.setObjectName("raport_button")
        self.horizontalLayout.addWidget(self.raport_button)
        self.generate_button = QtWidgets.QPushButton(self.frame_2)
        self.generate_button.setObjectName("generate_button")
        self.horizontalLayout.addWidget(self.generate_button)
        self.history_button = QtWidgets.QPushButton(self.frame_2)
        self.history_button.setObjectName("history_button")
        self.horizontalLayout.addWidget(self.history_button)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.inner_stackedWidget = QtWidgets.QStackedWidget(self.main_page)
        self.inner_stackedWidget.setObjectName("inner_stackedWidget")
        self.raport_page = QtWidgets.QWidget()
        self.raport_page.setObjectName("raport_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.raport_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.raport_textEdit = QtWidgets.QTextEdit(self.raport_page)
        self.raport_textEdit.setObjectName("raport_textEdit")
        self.gridLayout_4.addWidget(self.raport_textEdit, 0, 0, 1, 1)
        self.submitRaport_button = QtWidgets.QPushButton(self.raport_page)
        self.submitRaport_button.setObjectName("submitRaport_button")
        self.gridLayout_4.addWidget(self.submitRaport_button, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.inner_stackedWidget.addWidget(self.raport_page)
        self.generate_page = QtWidgets.QWidget()
        self.generate_page.setObjectName("generate_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.generate_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.generateRaport_button = QtWidgets.QPushButton(self.generate_page)
        self.generateRaport_button.setObjectName("generateRaport_button")
        self.gridLayout_6.addWidget(self.generateRaport_button, 0, 1, 1, 1)
        self.ownerPassword_lineEdit = QtWidgets.QLineEdit(self.generate_page)
        self.ownerPassword_lineEdit.setObjectName("ownerPassword_lineEdit")
        self.gridLayout_6.addWidget(self.ownerPassword_lineEdit, 0, 0, 1, 1)
        self.push_button = QtWidgets.QPushButton(self.generate_page)
        self.push_button.setObjectName("push_button")
        self.gridLayout_6.addWidget(self.push_button, 0, 2, 1, 1)
        self.generatedRaport_textEdit = QtWidgets.QTextEdit(self.generate_page)
        self.generatedRaport_textEdit.setObjectName("generatedRaport_textEdit")
        self.generatedRaport_textEdit.setReadOnly(True)
        self.gridLayout_6.addWidget(self.generatedRaport_textEdit, 1, 0, 1, 3)
        self.inner_stackedWidget.addWidget(self.generate_page)
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.history_page)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.history_textEdit = QtWidgets.QTextEdit(self.history_page)
        self.history_textEdit.setReadOnly(True)
        self.history_textEdit.setObjectName("history_textEdit")
        self.gridLayout_7.addWidget(self.history_textEdit, 0, 0, 1, 1)
        self.history_comboBox = QtWidgets.QComboBox(self.history_page)
        self.history_comboBox.setObjectName("history_comboBox")
        self.gridLayout_7.addWidget(self.history_comboBox, 0, 1, 1, 1)
        self.inner_stackedWidget.addWidget(self.history_page)
        self.gridLayout_5.addWidget(self.inner_stackedWidget, 1, 0, 1, 1)
        self.outer_stackedWidget.addWidget(self.main_page)
        self.gridLayout.addWidget(self.outer_stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        # stylesheets for windows
        if platform == 'win32' or platform == 'win64':
            MainWindow.setStyleSheet("background-color: #31363A;")
            self.raport_textEdit.setStyleSheet("background-color: #222629; color: white;")
            self.history_textEdit.setStyleSheet("background-color: #222629; color: white;")
            self.generatedRaport_textEdit.setStyleSheet("background-color: #222629; color: white;")
            self.raport_button.setStyleSheet("color: white;")
            self.generate_button.setStyleSheet("color: white;")
            self.history_button.setStyleSheet("color: white;")

        self.retranslateUi(MainWindow)
        self.outer_stackedWidget.setCurrentIndex(0)
        self.inner_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ReportApp"))
        self.name_lineEdit.setToolTip(_translate("MainWindow", "Provide name"))
        self.name_lineEdit.setPlaceholderText(_translate("MainWindow", "Name"))
        self.surname_lineEdit.setPlaceholderText(_translate("MainWindow", "Surname"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
        self.raport_button.setText(_translate("MainWindow", "Raport"))
        self.generate_button.setText(_translate("MainWindow", "Generate"))
        self.history_button.setText(_translate("MainWindow", "History"))
        self.raport_textEdit.setPlaceholderText(_translate("MainWindow", "Provide you daily raport here"))
        self.submitRaport_button.setText(_translate("MainWindow", "Submit"))
        self.generateRaport_button.setText(_translate("MainWindow", "Generate"))
        self.ownerPassword_lineEdit.setPlaceholderText(_translate("MainWindow", "Database owner password"))
        self.push_button.setText(_translate("MainWindow", "Push"))
